### ISSUE TITLE
Show me the toast 

### ISSUE THREAD

**Issue by simonexmachina** [cocotutch/toaster-ios#1]
What do they look like?

**Comment by viewDidAppear** [comment]
I had a talk to Sir Toaster of Kitchenshire and His Loyal Subjects regarding this matter. They were a bit Camera shy, but I promised to use real Butter and not that "plant crap" if they agreed. So they did! Please see the screenshot attached on the main page. :+1:

**Comment by simonexmachina** [comment]
Jolly good show old chap! Jolly good show indeed. Please do send my very best regards to Sir Toaster and subjects etc. etc.

Please forgive me, but I feel compelled to mention that you have misquoted Old Bill in your toast. The exact wording is as follows, I do hope you can excuse my presumptuousness!

> O Romeo, Romeo! Wherefore art thou Romeo?
> Deny thy father and refuse thy name.
